name: game_wiki_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_modular: ^6.3.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  auto_size_text: ^3.0.0
  dartz: ^0.10.1
  shimmer: ^3.0.0
  dio: ^5.4.0
  lottie: ^3.1.0
  flutter_riverpod: ^2.5.1
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
